# SPDX-License-Identifier: GPL-2.0
subdir-y += actions
subdir-y += al
subdir-y += allwinner
subdir-y += altera
subdir-y += amd
subdir-y += amlogic
subdir-y += apm
subdir-y += arm
subdir-y += bitmain
subdir-y += broadcom
subdir-y += cavium
subdir-y += exynos
subdir-y += freescale
subdir-y += hisilicon
subdir-y += intel
subdir-y += lg
subdir-y += marvell
subdir-y += mediatek
subdir-y += nvidia
subdir-y += qcom
subdir-y += realtek
subdir-y += renesas
subdir-y += rockchip
subdir-y += socionext
ifeq ($(TARGET_PRODUCT),ShadowcatPlus_Natv)
subdir-y += sprd_scp
else ifeq ($(TARGET_PRODUCT),Shadowcat_Natv)
subdir-y += sprd_scp
else ifeq ($(TARGET_PRODUCT),Magik_Natv)
subdir-y += sprd_magik
else
subdir-y += sprd
endif
subdir-y += synaptics
subdir-y += ti
subdir-y += xilinx
subdir-y += zte
